name:  Deploy

on:
  push:
    branches: [ main ]

jobs:
        
  deploy-staging:
    name: Deploy to staging test
    runs-on: cb
    steps:
      - run: echo ${newvar} Deploy to staging using 
        
  deploy-production:
    name: Deploy to production
    needs: [deploy-staging]
    runs-on: cb
    steps:
      - run: echo ${newvar} Deploy to production using 
